version: "3.9"

services:
  backend:
    container_name: backend
    image: ghcr.io/ak9024/okr-generator/backend:latest
    networks:
      - okr-generator-net

  frontend:
    container_name: frontend
    image: ghcr.io/ak9024/okr-generator/frontend:latest
    networks:
      - okr-generator-net

  caddy:
    image: caddy:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    networks:
      - okr-generator-net

networks:
  okr-generator-net:
