version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        PORT: "3000"
        HOST: "localhost"
        ENV: "production"
        VERSION: "v0.1.0"
        TOKEN: ""
        GOOGLE_CLIENT_ID: ""
        GOOGLE_CLIENT_SECRET: ""
        GOOGLE_REDIRECT_URL: ""
        GOOGLE_AUTH_STATE: ""
        SUPABASE_URL: ""
        SUPABASE_KEY: ""
    image: backend
    ports:
      - "3000:3000"
