// Package docs GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import (
	"bytes"
	"encoding/json"
	"strings"
	"text/template"

	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/okr-generator": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "OKR Generator",
                "parameters": [
                    {
                        "description": "OKRGeneratorRequest",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/okr.OKRGeneratorRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OKRGeneratorResponse200",
                        "schema": {
                            "$ref": "#/definitions/okr.OKRGeneratorResponse200"
                        }
                    },
                    "400": {
                        "description": "OKRGeneratorResponseError",
                        "schema": {
                            "$ref": "#/definitions/okr.OKRGeneratorResponseError"
                        }
                    },
                    "500": {
                        "description": "OKRGeneratorResponseError",
                        "schema": {
                            "$ref": "#/definitions/okr.OKRGeneratorResponseError"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "okr.KeyResult": {
            "type": "object",
            "properties": {
                "key_result": {
                    "type": "string"
                }
            }
        },
        "okr.OKRGeneratorRequest": {
            "type": "object",
            "required": [
                "objective",
                "translate"
            ],
            "properties": {
                "objective": {
                    "type": "string"
                },
                "translate": {
                    "type": "string"
                }
            }
        },
        "okr.OKRGeneratorResponse200": {
            "type": "object",
            "properties": {
                "key_results": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/okr.KeyResult"
                    }
                },
                "objective": {
                    "type": "string"
                },
                "status_code": {
                    "type": "integer"
                }
            }
        },
        "okr.OKRGeneratorResponseError": {
            "type": "object",
            "properties": {
                "messages": {},
                "status_code": {
                    "type": "integer"
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "",
	Host:        "",
	BasePath:    "",
	Schemes:     []string{},
	Title:       "",
	Description: "",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
		"escape": func(v interface{}) string {
			// escape tabs
			str := strings.Replace(v.(string), "\t", "\\t", -1)
			// replace " with \", and if that results in \\", replace that with \\\"
			str = strings.Replace(str, "\"", "\\\"", -1)
			return strings.Replace(str, "\\\\\"", "\\\\\\\"", -1)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register("swagger", &s{})
}
