definitions:
  okr.KeyResult:
    properties:
      key_result:
        type: string
    type: object
  okr.OKRGeneratorRequest:
    properties:
      objective:
        type: string
      translate:
        type: string
    required:
    - objective
    - translate
    type: object
  okr.OKRGeneratorResponse200:
    properties:
      key_results:
        items:
          $ref: '#/definitions/okr.KeyResult'
        type: array
      objective:
        type: string
      status_code:
        type: integer
    type: object
  okr.OKRGeneratorResponseError:
    properties:
      messages: {}
      status_code:
        type: integer
    type: object
info:
  contact: {}
paths:
  /api/v1/okr-generator:
    post:
      consumes:
      - application/json
      parameters:
      - description: OKRGeneratorRequest
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/okr.OKRGeneratorRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OKRGeneratorResponse200
          schema:
            $ref: '#/definitions/okr.OKRGeneratorResponse200'
        "400":
          description: OKRGeneratorResponseError
          schema:
            $ref: '#/definitions/okr.OKRGeneratorResponseError'
        "500":
          description: OKRGeneratorResponseError
          schema:
            $ref: '#/definitions/okr.OKRGeneratorResponseError'
      summary: OKR Generator
swagger: "2.0"
