name: Build & Push Backend

on:
  pull_request:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Dockerhub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build & Push
        uses: docker/build-push-action@v4
        with:
          context: "{{defaultContext}}:backend"
          tags: "${{ secrets.DOCKER_USERNAME }}/backend:latest"
          push: true
          build-args: |
            HOST=${{ secrets.HOST }}
            PORT=${{ secrets.PORT }}
            VERSION=${{ secrets.VERSION }}
            TOKEN=${{ secrets.TOKEN }}
            GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}
            GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}
            GOOGLE_REDIRECT_URL=${{ secrets.GOOGLE_REDIRECT_URL }}
            GOOGLE_CLIENT_REDIRECT_URL=${{ secrets.GOOGLE_CLIENT_REDIRECT_URL }}
            SUPABASE_URL=${{ secrets.SUPABASE_URL }}
            SUPABASE_KEY=${{ secrets.SUPABASE_KEY }}
