name: Deploy backend

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEYS }}
          script: |
            docker pull "${{ secrets.DOCKER_USERNAME }}/backend:latest"; \
            docker run -d "${{ secrets.DOCKER_USERNAME }}/backend:latest"
