name: Deploy

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEYS }}
          script: whoami
      - name: Build Docker Image
        run: |
          cd backend \
          docker build --build-arg HOST=${{ secrets.HOST }} --build-arg PORT=${{ secrets.PORT }} \
          --build-arg VERSION=${{ secrets.VERSION }} --build-arg TOKEN=${{ secrets.TOKEN }} \
          --build-arg GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }} --build-arg GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }} \
          --build-arg GOOGLE_REDIRECT_URL=${{ secrets.GOOGLE_REDIRECT_URL }} --build-arg GOOGLE_CLIENT_REDIRECT_URL=${{ secrets.GOOGLE_CLIENT_REDIRECT_URL }} \
          --build-arg SUPABASE_URL=${{ secrets.SUPABASE_URL }} --build-arg SUPABASE_KEY=${{ secrets.SUPABASE_KEY }} \
          -t "${{ secrets.DOCKER_USERNAME }}/backend:${{ github.sha }}" .
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
