name: Deploy

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEYS }}
          script: |
            docker stop $(docker ps -q -a)
            docker rm $(docker ps -q -a)
            docker image rmi $(docker images -q -a)
            docker pull "${{ secrets.DOCKER_USERNAME }}/backend:latest";
            docker run -d -p 3000:3000 "${{ secrets.DOCKER_USERNAME }}/backend:latest"
            docker pull "${{ secrets.DOCKER_USERNAME }}/frontend:latest";
            docker run -d -p 80:80 -p 443:443 "${{ secrets.DOCKER_USERNAME }}/frontend:latest"
            docker pull certbot/certbot
            docker run -it --rm \
            certbot/cerbot certonly \
            --webroot --webroot-path=/var/www/html \
            -d malascoding.com
